models.py
from datetime import datetime
from app import db
from flask_security import UserMixin, RoleMixin
import re




def slugify(title):
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', title)


post_tags = db.Table(
		'post_tags',
		db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
		db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
	)

class Post(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique = True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()

	tags = db.relationship('Tag', secondary = post_tags, backref = db.backref('posts', lazy = 'dynamic'))

	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id: {0}, title: {1}>'.format(self.id, self.title)

class Tag(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100))
	slug = db.Column(db.String(100))


	def __init__(self, *args, **kwargs):
		super(Tag, self).__init__(*args, **kwargs)
		self.slug = slugify(self.name)

	def __repr__(self):
		return '{}'.format(self.name)


### Auth ###


roles_users = db.Table(
	'roles_users',
	db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
	db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
	)


class User(db.Model, UserMixin):
	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(100), unique = True)
	password = db.Column(db.String(255))
	active = db.Column(db.Boolean())
	roles = db.relationship('Role', secondary=roles_users, backref = db.backref('users', lazy = 'dynamic'))


class Role(db.Model, RoleMixin):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100), unique = True)
	description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
	title = StringField('Title')
	body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask import redirect, url_for, request

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security
from flask_security import current_user



app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)



### ADMIN ###
from models import *

class AdminMixin:
	def is_accessible(self):
		return current_user.has_role('admin')

	def inaccessible_callback(self, name, **kwargs):
		return redirect(url_for('security.login', next = request.url))

class BaseModelView(ModelView):
	def on_model_change(self, form, model, is_created):
		model.generate_slug()
		return super(BaseModelView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
	pass


class HomeAdminView(AdminMixin, AdminIndexView):
	pass


class PostAdminView(AdminMixin, BaseModelView):
	form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
	form_columns = ['name', 'posts']

admin = Admin(app, 'FlaskApp', url = '/', index_view = HomeAdminView(name = 'Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))







### flask-security ###
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from posts.blueprint import posts

app = Flask(__name__)
app.config.from_object(Configuration)

app.register_blueprint(posts, url_prefix='/blog')

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
	return render_template('posts/index.html')

main.py
#! ../venv/bin/python3

from app import app
import view
from posts.blueprint import posts

from models import Post

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
	app.run()

posts/blueprint.py
from flask import Blueprint, request
from flask import render_template, redirect, url_for

from models import Post, Tag
from .forms import PostForm, PostForm

from app import db

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder = 'templates')


# /blog/create

@posts.route('/create', methods = ['POST', 'GET'])
@login_required
def create_post():

	if request.method == 'POST':
		title = request.form['title']
		body = request.form['body']

		try:
			post = Post(title = title, body = body)
			db.session.add(post)
			db.session.commit()
		except:
			print('Error!!!!')

		return redirect( url_for('posts.index'))


	form = PostForm()
	return render_template('posts/create_post.html', form = form)



# @posts.route('/<slug>/edit', methods=['POST', 'GET'])
# @login_required
# def edit_post(slug):
# 	post = Post.query.filter(Post.slug==slug).first_or_404()
# 	if request.method == 'POST':
# 		form = EditPostForm(formdata=request.form, obj=post)
# 		form.populate_obj(post)
# 		db.session.commit()

# 		return redirect(url_for('posts.post_details', slug = post.slug))

# 	form = PostForm(obj = post)
# 	return render_template('posts/edit_post.html', post=post, form = form)



# /blog/
@posts.route('/')
def index():

	q = request.args.get('q')
	page = request.args.get('page')

	if page and page.isdigit():
		page = int(page)
	elif page:
		page = 1


	if q:
		posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
	else:
		posts = Post.query.order_by(Post.id.desc())

	pages = posts.paginate(page=page, per_page=4)

	return render_template('posts/index.html', pages = pages)


# /blog/post-name
@posts.route('/<slug>')
def post_details(slug):
	post = Post.query.filter(Post.slug == slug).first_or_404()
	tags = post.tags
	return render_template('posts/post_full.html', post = post, tags = tags)

# /blog/tag/tag-slug
@posts.route('/tag/<slug>')
def tag_datails(slug):
	tag = Tag.query.filter(Tag.slug == slug).first_or_404()
	posts = tag.posts.all()
	return render_template('posts/tags_posts.html', tag = tag, posts = posts)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}-Flask</title>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ url_for('index') }}">Flask Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('posts.index')}}">Blog</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
        <h1>
            {% block content_title %}
            {% endblock %}
        </h1>
    <div class="row">
        <p>
            {% block content %}
            {% endblock %}
        </p>    
  </div>
</div>


</body>
</html>

posts/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
	Create new post
{% endblock %}



{% block content_title %}
	New Post
{% endblock %}


{% block content %}
	
<div class="col-md-6">
	<form action="{{ url_for('posts.create_post') }}" method = 'Post'>
		
		{% for fi in form %}
			
			<div class="form-group">
				{{ fi.label(class ='control-label') }}
				{{ fi(class='form-control') }}
			</div>

		{% endfor %}
		<button type="submit" class="btn btn-success">Create post</button>
	</form>
</div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}


{% block title %}
	Edit post
{% endblock %}



{% block content_title %}
	Edit post
{% endblock %}


{% block content %}
	
<div class="col-md-6">
	<form action="{{ url_for('posts.edit_post', slug = post.slug) }}" method = 'POST'>
		
		{% for field in form %}
			
			<div class="form-group">
				{{ field.label(class ='control-label') }}
				{{ field(class='form-control') }}
			</div>

		{% endfor %}

		<button type="submit" class="btn btn-success">Finish edit</button>
	</form>
</div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
	Blueprint
{% endblock %}


{% block content_title %}
	All Posts:
{% endblock %}

{% block content %}
		<div class="card" style="width: 18rem;">
			<ul class="list-group list-group-flush">
				{% for post in pages.items %}
					<li class="list-group-item"><a href="{{url_for('posts.post_details', slug = post.slug)}}">{{ post.title }}</a></li>
				{% endfor %}
			</ul>
		</div>


		<nav>
			<ul class="pagination">
				<li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
					<a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
				</li>
				{% for page in pages.iter_pages() %}
					<li {% if page ==pages.page %} class="page-item active" {% endif %}>
						<a class="page-link" href="./?page={{ page }}">{{ page }}</a>
					</li>
				{% endfor %}
				
				<li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
					<a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
						<span class="sr-only">Next</span>
					</a>
				</li>
			</ul>
		</nav>
{% endblock %}

posts/templates/posts/post_full.html
{% extends 'base.html' %}



{% block title %}
	{{ post.title }}
{% endblock %}

<div class="d-flex justify-content-center flex-fill">
	{% block content %}
			<div class="card text-white bg-dark mb-3" style="max-width: 55rem;">
				<div class="card-body">
					<h5 class="card-title text-center">{{ post.title }}</h5>
					{% for tag in tags %}
						<a href="{{ url_for('posts.tag_datails', slug = tag.slug) }}">
							<span class="badge badge-success">{{ tag.name }}</span>
						</a>
					{% endfor %}
					<p class="card-text">{{ post.body }}</p>
				</div>
			</div>
	{% endblock %}
</div>

posts/templates/posts/tags_posts.html
{% extends 'base.html' %}

{% block title %}
	{{ tag.name }} posts
{% endblock %}



{% block content_title %}
	Posts for tag "{{ tag.name }}":
{% endblock %}


{% block content %}
<ul class="list-group">
	{% for post in posts %}
	<li class="list-group-item">
		<a href="{{ url_for('posts.post_details', slug = post.slug) }}">{{ post.title }}</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}

templates/about.html
{% extends 'base.html' %}



{% block title %}
	About
{% endblock %}


{% block content_title %}
	About
{% endblock %}

{% block content %}
	<div class="content">
		<p>This site was created to demonstrate the basic features of Flask</p>
		<p>Этот сайт создан для демонстрации базовых возможностей Flask </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum neque in quaerat quae, a voluptatum accusamus, eos pariatur non sequi iste facere obcaecati eveniet dolore voluptate omnis esse velit soluta at, tempora est. Natus quia dolorem consectetur laudantium aperiam ullam soluta accusamus! Cumque ducimus tempora nostrum eum voluptate optio ab aspernatur nihil, explicabo nesciunt earum ratione accusantium quis iste magni amet iusto eos nam, laudantium repellat consectetur neque necessitatibus alias porro. Ullam tempora tenetur amet repellendus perspiciatis! Facilis voluptatum, laborum, at vero sint quo. Sapiente officiis, repudiandae velit accusamus quod dolorem recusandae in itaque quasi consequuntur perferendis adipisci amet saepe.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde ipsum neque fugit sed eos temporibus voluptates, atque odio. Earum minima possimus est esse placeat! Officiis perspiciatis quos, culpa officia atque cumque fuga dolores deserunt placeat. Aliquam illum quidem ab doloremque.</p>
	</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}| Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('index') }}">Flask Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.index')}}">Blog</a>
                </li>
                <li>
                    <a class="nav-link" href = "{{ url_for('about') }}">About</a>
                </li>
                <li class="nav-item">
                    <!-- <a class = "nav-link" href="{{ url_for('posts.create_post') }}">+Create new</a> -->
                    <li class="nav-item">
                        {% if current_user.has_role('admin') %}
                            <a href="/admin" class = "nav-link">Admin</a>
                        {% endif %}
                    </li>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0" method="GET">

                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            </form>

        </ul>
    </div>
</nav>

<div class="container col-md-9">
    <h1>
        {% block content_title %}
        {% endblock %}
    </h1>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block content_title %}
	Index page
{% endblock %}

{% block content %}
	<p>Главная страница этого блога, созданного для примера и чтобы закрепить знания в базах данных, оформления форм, создания url-ов, миграции, и т.д</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro nulla totam laborum ex, laboriosam repudiandae autem molestiae, aut ab qui nostrum officiis sint numquam sapiente. Cumque neque facere doloribus suscipit mollitia dolores, quasi molestiae dicta optio id non impedit ducimus debitis veniam eius natus nihil qui reprehenderit perspiciatis voluptatum dolorum.</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, suscipit quaerat explicabo dolore quis commodi, autem minus ratione tempora pariatur totam nesciunt veniam fugit ullam repellat maiores, consectetur dolorum nulla ad porro cupiditate debitis voluptatem id modi assumenda? Consequatur quaerat, quidem dolor recusandae, temporibus ab asperiores, maiores itaque commodi vero animi officia blanditiis esse eos alias tempora aut culpa. Ratione, ullam! Adipisci expedita, tempore enim quae aspernatur quaerat iste in quibusdam? Sapiente excepturi aliquid maiores.</p>
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}



{% block content %}
<div class = "d-flex justify-content-center">
	<div class="col-md-6">
	{% from "security/_macros.html" import render_field_with_errors, render_field %}
	{% include "security/_messages.html" %}
	<h2>{{ _('Login') }}</h2>
		<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
		  {{ login_user_form.hidden_tag() }}
		  {{ render_field_with_errors(login_user_form.email, class = 'form-control') }}
		  {{ render_field_with_errors(login_user_form.password, class = 'form-control') }}
		  {{ render_field_with_errors(login_user_form.remember) }}
		  {{ render_field(login_user_form.next) }}
		  {{ render_field(login_user_form.submit, class = 'btn btn-success') }}
		</form>
	</div>
</div>
{% endblock %}
{% include "security/_menu.html" %}